### ISSUE TITLE
проверить задачу 46 исправил

### ISSUE THREAD

**Issue by ovsianka17e** [ovsianka17e/my-work#3]

**Comment by andrewbudo** [comment]
Проверено, решение отсутствует.

**Comment by andrewbudo** [comment]
Как получена эта формула?
</br> <img src="https://latex.codecogs.com/svg.image?m_{\beta&space;}^{2}=&space;m_{2}^{2}&plus;&space;m_{1}^{2}" title="m_{\beta }^{2}= m_{2}^{2}+ m_{1}^{2}" />
Решение должно быть подробным.
Не зачтено.

**Comment by ovsianka17e** [comment]
Здравствуйте, сколько задач нужно верно решить для автомата
